### ISSUE TITLE
P::explode not accepting empty string delimiter

### ISSUE THREAD

**Issue by mmikeyy** [mpajunen/phamda#1]
A big oops.... It's in javascript that strings can be split with an empty delimiter, not in PHP.  Disregard this issue!!

Just wondering what's the point of refusing an empty string as a delimiter for P::explode. The std PHP explode function simply returns an array of all characters when called with an empty delimiter, which is convenient.

**Comment by mpajunen** [comment]
While the PHP native  `explode()` doesn't allow an empty delimiter, I think it can be useful to allow in Phamda.
